Baca sumber data dari google drive

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Impor Library

In [14]:
import pandas as pd

Baca data

In [15]:
df=pd.read_csv("drive/MyDrive/pandas/Data/airbnb.csv")

Melihat beberapa data awal dari dataframe

In [16]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [18]:
df.shape

(48895, 16)

Untuk mengatur index gunakan fungsi set_index(“nama_column”). Pada contoh, dibuat dataframe kedua untuk menyimpan data dengan index baru

In [19]:
#new dataframe
df2 = df.set_index("host_name")
df2.head(10)

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
John,2539,Clean & quiet apt home by the park,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
Jennifer,2595,Skylit Midtown Castle,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
Elisabeth,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
LisaRoxanne,3831,Cozy Entire Floor of Brownstone,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
Laura,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
Chris,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
Garon,5121,BlissArtsSpace!,7356,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,2017-10-05,0.40,1,0
Shunichi,5178,Large Furnished Room Near B'way,8967,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,2019-06-24,3.47,1,220
MaryEllen,5203,Cozy Clean Guest Room - Family Apt,7490,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,2017-07-21,0.99,1,0
Ben,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,2019-06-09,1.33,4,188

Juga bisa mengubah langsung pada dataframe pertama. Lihat code kedua, menggunakan parameter inplace=True

In [20]:
#inplace
df.set_index("id", inplace=True)

Untuk sorting, dapat digunakan fungsi sort_values(by=”nama_kolom”). Jika hasil sorting ingin diaplikasikan pada dataframe bersangkutan, gunakan parameter inplace=True

In [21]:
#inplace, sorting diaplikasikan pada dataframe
df.sort_values(by="host_name", ascending=False, inplace=True)

#hasil sorting akan disimpan di dataframe kedua
df2 = df.sort_values(by="host_name", ascending=False)

In [22]:
df.sort_values(by=["neighbourhood_group", "host_name"])

#mengatur order
df.sort_values(by=["neighbourhood_group", "host_name"], ascending=[False, True])

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,,
13370393,Charming.,13373889,Aaron,Staten Island,Concord,40.60556,-74.08274,Entire home/apt,150,7,1,2018-11-04,0.12,2,83
2611458,close to Manhattan country setting,13373889,Aaron,Staten Island,Concord,40.60375,-74.08065,Private room,129,1,40,2018-10-14,0.85,2,86
19970350,Newly renovated clean and Cozy Private room,15344412,Abe,Staten Island,New Springville,40.58085,-74.15443,Private room,43,10,0,NaN,NaN,3,89
23998608,Cozy room with a comfortable bed,15344412,Abe,Staten Island,New Springville,40.57942,-74.15506,Private room,50,1,38,2019-06-23,2.64,3,88
20886536,Comfortable stay,15344412,Abe,Staten Island,New Springville,40.58091,-74.15485,Private room,52,1,74,2019-06-25,3.34,3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18852048,"Clean, spacious and comfortable room at Bronx",108922928,Zeeshan,Bronx,Allerton,40.85961,-73.86361,Private room,49,3,1,2017-06-01,0.04,1,0
23026346,"A Nice 3 Bedroom Apt in Pelham Bay, Bronx, NY.",170857849,Ziaul,Bronx,Pelham Bay,40.84934,-73.83345,Entire home/apt,119,3,28,2019-06-12,1.68,1,351
35131221,Apartment in Riverdale NY,264618293,Zlatan,Bronx,Fieldston,40.89701,-73.89778,Entire home/apt,109,2,1,2019-07-01,1.00,1,192
26304871,New York City (Downtown) accessibly sleeps 6,197794017,Zoraida,Bronx,Bronxdale,40.85456,-73.86921,Entire home/apt,79,2,36,2019-06-24,3.33,1,10
15648096,Spacious 2 bedroom close to Manhattan,100971588,NaN,Bronx,Highbridge,40.83844,-73.92489,Entire home/apt,75,4,37,2019-07-07,1.21,1,26

Jika tidak menggunakan parameter inplace, buat variabel untuk menampung dataframe baru

In [23]:
#hasil sorting akan disimpan di dataframe kedua
df2 = df.sort_values(by="host_name", ascending=False)
df2

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,,
26139678,Private cozy room in perfect UWS,18497228,현선,Manhattan,Morningside Heights,40.80485,-73.96534,Private room,1200,60,0,NaN,NaN,1,365
22392030,one bedroom apt for long term stay up to 2 months,151728547,진,Manhattan,Upper West Side,40.77506,-73.98162,Entire home/apt,70,15,0,NaN,NaN,1,0
26834353,Cozy Brooklyn Room - Next to Pratt Institute,133425456,소정,Brooklyn,Bedford-Stuyvesant,40.69056,-73.95980,Private room,40,5,1,2018-08-18,0.09,1,0
35662019,Cheap price near Timesquare,79269209,소정,Manhattan,Hell's Kitchen,40.75625,-73.99357,Private room,63,31,0,NaN,NaN,1,250
32554746,"Clean, Safe, east village room!",112439306,빈나,Manhattan,Stuyvesant Town,40.73180,-73.97999,Private room,125,4,1,2019-03-06,0.24,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21901156,Best Deal! Lovely place in Manhattan! Time Squ...,159156636,NaN,Manhattan,Hell's Kitchen,40.75656,-73.99063,Private room,120,1,109,2019-01-01,5.97,3,0
21990808,***SLEEPING IN THE GOLDEN PLACE***,159156636,NaN,Manhattan,Hell's Kitchen,40.75835,-73.99065,Private room,120,1,88,2018-12-14,4.93,3,0
23660605,Private Bedroom w/ Balcony view of Central Park,177146433,NaN,Manhattan,East Harlem,40.79766,-73.94824,Private room,139,1,6,2018-08-12,0.46,1,0
25180572,Beautiful Cozy Studio Apt. UWS,119609345,NaN,Manhattan,Upper West Side,40.77701,-73.97667,Entire home/apt,180,4,0,NaN,NaN,1,0
30468335,LARGE Prospect Lefferts Gardens Bedroom,228750026,NaN,Brooklyn,Flatbush,40.65152,-73.95271,Private room,55,7,0,NaN,NaN,1,69

Sorting juga bisa dilakukan pada 2 kolom, dan bisa diatur ordernya tiap kolom

In [24]:
df.sort_values(by=["neighbourhood_group", "host_name"])
#mengatur order
df.sort_values(by=["neighbourhood_group", "host_name"], ascending=[False, True])

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,,
13370393,Charming.,13373889,Aaron,Staten Island,Concord,40.60556,-74.08274,Entire home/apt,150,7,1,2018-11-04,0.12,2,83
2611458,close to Manhattan country setting,13373889,Aaron,Staten Island,Concord,40.60375,-74.08065,Private room,129,1,40,2018-10-14,0.85,2,86
19970350,Newly renovated clean and Cozy Private room,15344412,Abe,Staten Island,New Springville,40.58085,-74.15443,Private room,43,10,0,NaN,NaN,3,89
23998608,Cozy room with a comfortable bed,15344412,Abe,Staten Island,New Springville,40.57942,-74.15506,Private room,50,1,38,2019-06-23,2.64,3,88
20886536,Comfortable stay,15344412,Abe,Staten Island,New Springville,40.58091,-74.15485,Private room,52,1,74,2019-06-25,3.34,3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18852048,"Clean, spacious and comfortable room at Bronx",108922928,Zeeshan,Bronx,Allerton,40.85961,-73.86361,Private room,49,3,1,2017-06-01,0.04,1,0
23026346,"A Nice 3 Bedroom Apt in Pelham Bay, Bronx, NY.",170857849,Ziaul,Bronx,Pelham Bay,40.84934,-73.83345,Entire home/apt,119,3,28,2019-06-12,1.68,1,351
35131221,Apartment in Riverdale NY,264618293,Zlatan,Bronx,Fieldston,40.89701,-73.89778,Entire home/apt,109,2,1,2019-07-01,1.00,1,192
26304871,New York City (Downtown) accessibly sleeps 6,197794017,Zoraida,Bronx,Bronxdale,40.85456,-73.86921,Entire home/apt,79,2,36,2019-06-24,3.33,1,10
15648096,Spacious 2 bedroom close to Manhattan,100971588,NaN,Bronx,Highbridge,40.83844,-73.92489,Entire home/apt,75,4,37,2019-07-07,1.21,1,26