In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Pertama import library yang digunakan, lalu load data.

In [3]:
import pandas as pd

students = pd.read_csv("drive/MyDrive/pandas/Data/merging/students.csv")
teachers = pd.read_csv("drive/MyDrive/pandas/Data/merging/teachers.csv")
grades1 = pd.read_csv("drive/MyDrive/pandas/Data/merging/grades1.csv")
grades2 = pd.read_csv("drive/MyDrive/pandas/Data/merging/grades2.csv")
contacts = pd.read_csv("drive/MyDrive/pandas/Data/merging/contact.csv")

# Menambahkan Kolom

Kita tambahkan kolom semester pada dataframe grades1 dan grades2. Lalu gabungkan menjadi satu dataframe grades dengan perintah concat.

In [4]:
grades1["Semester"] = 1
grades2["Semester"] = 2

grades = pd.concat([grades1, grades2])

Jika kita lihat isi dataframe grades, kurang lebih seperti berikut.

In [5]:
grades

    student_id   course grade  Semester
0        34292  ENGL101     A         1
1        34293  ENGL101     A         1
2        34294  ENGL101     C         1
3        34295  ENGL101     C         1
4        34296  ENGL101     C         1
..         ...      ...   ...       ...
60       34312  DESN101     E         2
61       34313  DESN101     D         2
62       34314  DESN101     A         2
63       34315  DESN101     A         2
64       34316  DESN101     A         2

[190 rows x 4 columns]

Yang perlu diperhatikan adalah perintah concat tidak mengubah index dataframe. Perlu dilakukan reset_index. Parameter drop=True akan mengganti index lama dengan index baru dengan nilai incremental integer.

In [ ]:
grades = grades.reset_index(drop=True)

# Merging Horizontal

Contoh kasus: menggabungkan data student dan grade. Dataframe akhir akan berisi data seperti: idstudent, nama, course, grade, dan semester.

Boleh dikatakan merging horizontal seperti perintah SELECT pada SQL, dimana kita mendefinisikan WHERE dengan parameter left_on dan right_on.

Untuk lebih jelasnya lihat code dibawah. left_on diisi dengan id dari dataframe students, dan right_on diisi dengan student_id dari dataframe grades.

In [8]:
student_grades = pd.merge(students, grades, left_on="id", right_on="student_id")

Jika kita lihat, isi dataframe akan seperti berikut

In [9]:
grades

     student_id   course grade  Semester
0         34292  ENGL101     A         1
1         34293  ENGL101     A         1
2         34294  ENGL101     C         1
3         34295  ENGL101     C         1
4         34296  ENGL101     C         1
..          ...      ...   ...       ...
185       34312  DESN101     E         2
186       34313  DESN101     D         2
187       34314  DESN101     A         2
188       34315  DESN101     A         2
189       34316  DESN101     A         2

[190 rows x 4 columns]

Parameter lainnya yang perlu diperhatikan adalah how, terdapat 4 option.

# Menggunakan Join

Kita dapat gunakan perintah join untuk merging dataframe. Perintah join harus menggunakan index sebagai primary key.

Contoh skenario menggabungkan data students dengan contact. Maka langkah pertama adalah mengatur index menggunakan kolom primary key.

Baru kemudian perintah join bisa digunakan untuk merge kedua dataframe.

In [7]:
students2 = students.set_index("id")
contacts2 = contacts.set_index("student_id")

students2.join(contacts2)

      firstname  lastname   parent_contact           phone
id
34292    Joshua     Davis     Samuel Davis  (356) 849-0352
34293     Karen    Flores     Laura Flores  (477) 325-7117
34294     Julia    Walker      Eric Walker  (871) 639-0797
34295   Cynthia  Robinson   Chris Robinson  (574) 683-2107
34296    Bonnie      Hall     Dorothy Hall  (384) 293-2113
34297  Gary Lee       Lee         Mary Lee  (914) 452-6366
34298      Ruby  Thompson    Jose Thompson  (253) 419-7702
34299   Heather    Miller     Annie Miller  (864) 583-9615
34300      Mary  Mitchell  Edward Mitchell  (494) 471-1604
34301    Carlos      Ross       Debra Ross  (592) 663-4425
34302   Dorothy     Green    Russell Green  (749) 344-5744
34303      Joan      Wood      Walter Wood  (457) 429-8627
34304      Judy     Jones       Lisa Jones  (773) 266-0693
34305     Nancy    Turner   Barbara Turner  (908) 350-9105
34306      Mark  Phillips  Jeremy Phillips  (600) 628-1550
34307   Gregory  Gonzales    Sara Gonzales  (588) 469-9488
34308     Shawn    Rivera    Joseph Rivera  (759) 260-4879
34309      Lois     James       Mark James  (762) 286-9877
34310   William   Sanders     Ruth Sanders  (249) 216-0443
34311   Barbara  Peterson   James Peterson  (584) 827-4997
34312   Douglas      Cook       Jimmy Cook  (364) 231-5641
34313     Helen     Allen   Lawrence Allen  (607) 356-7119
34314   Melissa     Price       Anne Price  (545) 667-7557
34315   Russell      Reed      Johnny Reed  (708) 871-9155
34316   Stephen  Martinez   Norma Martinez  (783) 439-7854