Untuk mengambil sebagian dataset dari sebuah dataframe, Anda dapat lakukan slicing. Slicing bisa dilakukan terhadap column atau row.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Anda bisa memilih kolom tertentu saja. Bisa single column atau multicolumn.

In [2]:
import pandas as pd

df = pd.read_csv("drive/MyDrive/pandas/Data/airbnb.csv")

#pendekatan array
df["host_name"]

#atau pendekatan dot
df.host_name

#multicolumn
df[["host_name", "neighbourhood_group"]]

           host_name neighbourhood_group
0               John            Brooklyn
1           Jennifer           Manhattan
2          Elisabeth           Manhattan
3        LisaRoxanne            Brooklyn
4              Laura           Manhattan
...              ...                 ...
48890        Sabrina            Brooklyn
48891        Marisol            Brooklyn
48892  Ilgar & Aysel           Manhattan
48893            Taz           Manhattan
48894     Christophe           Manhattan

[48895 rows x 2 columns]

# Filtering DataFrame

Contohnya tampilkan data dengan host_name= “Taz”.

In [3]:
df[df.host_name == "Taz"]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
31463,24491624,43rd Street=TIME SQUARE\nPRIVATE BEDROOM,30985759,Taz,Manhattan,Hell's Kitchen,40.75780,-73.99211,Private room,116,1,95,2019-07-04,6.42,6,280
31517,24539281,43rd Street “TIME SQUARE”\nSingle bed.,30985759,Taz,Manhattan,Hell's Kitchen,40.75792,-73.99172,Shared room,65,1,108,2019-06-23,7.33,6,325
37598,29827403,“TIME SQUARE” 43rd Street\nBig Bedroom on 1st ...,30985759,Taz,Manhattan,Hell's Kitchen,40.75988,-73.99123,Private room,135,1,50,2019-07-07,6.20,6,316
37615,29831106,TIME SQUARE” 43rd street\nPrivate room on 1st ...,30985759,Taz,Manhattan,Hell's Kitchen,40.75938,-73.98986,Private room,145,1,61,2019-07-06,7.50,6,283
37795,29929331,“TIME SQUARE” 43rd street SINGLE BED,30985759,Taz,Manhattan,Hell's Kitchen,40.75964,-73.99002,Shared room,70,1,59,2019-07-04,7.47,6,314
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2

Jika logic filtering rumit, Anda bisa buat aturan filter dalam variable.

In [4]:
mask = df.host_name == "Taz"
df[mask]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
31463,24491624,43rd Street=TIME SQUARE\nPRIVATE BEDROOM,30985759,Taz,Manhattan,Hell's Kitchen,40.75780,-73.99211,Private room,116,1,95,2019-07-04,6.42,6,280
31517,24539281,43rd Street “TIME SQUARE”\nSingle bed.,30985759,Taz,Manhattan,Hell's Kitchen,40.75792,-73.99172,Shared room,65,1,108,2019-06-23,7.33,6,325
37598,29827403,“TIME SQUARE” 43rd Street\nBig Bedroom on 1st ...,30985759,Taz,Manhattan,Hell's Kitchen,40.75988,-73.99123,Private room,135,1,50,2019-07-07,6.20,6,316
37615,29831106,TIME SQUARE” 43rd street\nPrivate room on 1st ...,30985759,Taz,Manhattan,Hell's Kitchen,40.75938,-73.98986,Private room,145,1,61,2019-07-06,7.50,6,283
37795,29929331,“TIME SQUARE” 43rd street SINGLE BED,30985759,Taz,Manhattan,Hell's Kitchen,40.75964,-73.99002,Shared room,70,1,59,2019-07-04,7.47,6,314
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2

Negasi juga bisa digunakan untuk filter. Pada contoh filter untuk host_name == “Taz”, kita ingin menampilkan semua data kecuali Taz.

In [5]:
mask = df.host_name == "Taz"
df[~mask]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48889,36484363,QUIT PRIVATE HOUSE,107716952,Michael,Queens,Jamaica,40.69137,-73.80844,Private room,65,1,0,NaN,NaN,2,163
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

Lebih lanjut, Anda bisa tambahkan operasi juga pada mask diatas, contoh fungsi sum().

In [6]:
mask = df.host_name == "Taz"
mask.sum()

#perintah mask diatas sama dengan
(df.host_name == "Taz").sum()

6

Filtering juga bisa lebih dari satu kolom, contoh ingin menampilkan data harga dibawah 100 dan minimum nights dibawah 3 malam.

In [7]:
filter2 = (df.price < 100) & (df.minimum_nights<3)
filter2.sum()

12129

# Filtering Column dan Row

Untuk menampilkan data dengan filtering column dan row, gunakan fungsi loc. Aturan Python slicing juga dapat digunakan.

In [8]:
#menampilkan data dengan filter mask, kolom host_name dan neighbourhood.
df.loc[mask, ["host_name", "neighbourhood_group"]]

#menampilkan data dengan filter mask, dari kolom host_name sampai dengan neighbourhood.
df.loc[mask, "host_id" : "neighbourhood_group"]

#menampilkan data dengan filter mask, seluruh kolom.
df.loc[mask, :]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
31463,24491624,43rd Street=TIME SQUARE\nPRIVATE BEDROOM,30985759,Taz,Manhattan,Hell's Kitchen,40.75780,-73.99211,Private room,116,1,95,2019-07-04,6.42,6,280
31517,24539281,43rd Street “TIME SQUARE”\nSingle bed.,30985759,Taz,Manhattan,Hell's Kitchen,40.75792,-73.99172,Shared room,65,1,108,2019-06-23,7.33,6,325
37598,29827403,“TIME SQUARE” 43rd Street\nBig Bedroom on 1st ...,30985759,Taz,Manhattan,Hell's Kitchen,40.75988,-73.99123,Private room,135,1,50,2019-07-07,6.20,6,316
37615,29831106,TIME SQUARE” 43rd street\nPrivate room on 1st ...,30985759,Taz,Manhattan,Hell's Kitchen,40.75938,-73.98986,Private room,145,1,61,2019-07-06,7.50,6,283
37795,29929331,“TIME SQUARE” 43rd street SINGLE BED,30985759,Taz,Manhattan,Hell's Kitchen,40.75964,-73.99002,Shared room,70,1,59,2019-07-04,7.47,6,314
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2

# Slicing berdasarkan index

Untuk slicing menggunakan index, gunakan fungsi iloc. Aturan Python slicing juga bisa digunakan.

In [9]:
#menampilkan data baris ke 0, kolom ketiga (host_name).

df.iloc[0, 3]

#mengembalikan 'John'


#menampilkna data baris ke 0, semua kolom
df.iloc[0, :]

id                                                              2539
name                              Clean & quiet apt home by the park
host_id                                                         2787
host_name                                                       John
neighbourhood_group                                         Brooklyn
neighbourhood                                             Kensington
latitude                                                    40.64749
longitude                                                  -73.97237
room_type                                               Private room
price                                                            149
minimum_nights                                                     1
number_of_reviews                                                  9
last_review                                               2018-10-19
reviews_per_month                                               0.21
calculated_host_listings_count                                     6
availability_365                                                 365
Name: 0, dtype: object

# Menggunakan Mask Helper

Mask helper adalah fungsi seperti between dan isin. Berikut contoh menampilkan data dengan harga antara 100 dan 200.

In [10]:
df.loc[df.price.between(100,200), ["host_name", "price"]].head()

    host_name  price
0        John    149
2   Elisabeth    150
5       Chris    200
9         Ben    150
10       Lena    135

Berikut adalah contoh menampilkan data dengan price adalah 100 atau 200.

In [11]:
df.loc[df.price.isin([100,200]), ["host_name", "price"]].head()

     host_name  price
5        Chris    200
54   Francesca    200
63     Dimitri    200
76    Victoria    200
94  Christiana    100